// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: redisbalance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ############以下部分为业务处理########
type BA_API_CMD int32

const (
	BA_API_CMD_BA_CMD_INVALID             BA_API_CMD = 0
	BA_API_CMD_BA_CMD_PING                BA_API_CMD = 1
	BA_API_CMD_BA_CMD_PONG                BA_API_CMD = 2
	BA_API_CMD_BA_CMD_GET_BALANCE_REQ     BA_API_CMD = 3 // 请求用户金额：CommonReq
	BA_API_CMD_BA_CMD_GET_BALANCE_RESP    BA_API_CMD = 4 // 返回用户余额：GetBalanceResp
	BA_API_CMD_BA_CMD_UPDATE_BALANCE_REQ  BA_API_CMD = 5 // 请求更新：UpdateBalanceReq
	BA_API_CMD_BA_CMD_UPDATE_BALANCE_RESP BA_API_CMD = 6 // 返回更新：GetBalanceResp
)

// Enum value maps for BA_API_CMD.
var (
	BA_API_CMD_name = map[int32]string{
		0: "BA_CMD_INVALID",
		1: "BA_CMD_PING",
		2: "BA_CMD_PONG",
		3: "BA_CMD_GET_BALANCE_REQ",
		4: "BA_CMD_GET_BALANCE_RESP",
		5: "BA_CMD_UPDATE_BALANCE_REQ",
		6: "BA_CMD_UPDATE_BALANCE_RESP",
	}
	BA_API_CMD_value = map[string]int32{
		"BA_CMD_INVALID":             0,
		"BA_CMD_PING":                1,
		"BA_CMD_PONG":                2,
		"BA_CMD_GET_BALANCE_REQ":     3,
		"BA_CMD_GET_BALANCE_RESP":    4,
		"BA_CMD_UPDATE_BALANCE_REQ":  5,
		"BA_CMD_UPDATE_BALANCE_RESP": 6,
	}
)

func (x BA_API_CMD) Enum() *BA_API_CMD {
	p := new(BA_API_CMD)
	*p = x
	return p
}

func (x BA_API_CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BA_API_CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_redisbalance_proto_enumTypes[0].Descriptor()
}

func (BA_API_CMD) Type() protoreflect.EnumType {
	return &file_redisbalance_proto_enumTypes[0]
}

func (x BA_API_CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BA_API_CMD.Descriptor instead.
func (BA_API_CMD) EnumDescriptor() ([]byte, []int) {
	return file_redisbalance_proto_rawDescGZIP(), []int{0}
}

// bonus结构，暂时不用
type PbBonus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BonusIndex uint32 `protobuf:"varint,1,opt,name=bonus_index,json=bonusIndex,proto3" json:"bonus_index,omitempty"`
	ExpireTime uint32 `protobuf:"varint,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	BonusValue int32  `protobuf:"varint,3,opt,name=bonus_value,json=bonusValue,proto3" json:"bonus_value,omitempty"` // 有正负
}

func (x *PbBonus) Reset() {
	*x = PbBonus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisbalance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbBonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbBonus) ProtoMessage() {}

func (x *PbBonus) ProtoReflect() protoreflect.Message {
	mi := &file_redisbalance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbBonus.ProtoReflect.Descriptor instead.
func (*PbBonus) Descriptor() ([]byte, []int) {
	return file_redisbalance_proto_rawDescGZIP(), []int{0}
}

func (x *PbBonus) GetBonusIndex() uint32 {
	if x != nil {
		return x.BonusIndex
	}
	return 0
}

func (x *PbBonus) GetExpireTime() uint32 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *PbBonus) GetBonusValue() int32 {
	if x != nil {
		return x.BonusValue
	}
	return 0
}

// account的定义
type PbBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance     int32 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`                            // 存款账户，有正负
	BalanceWins int32 `protobuf:"varint,2,opt,name=balance_wins,json=balanceWins,proto3" json:"balance_wins,omitempty"` // 可提现账户，有正负
	Practice    int32 `protobuf:"varint,3,opt,name=practice,proto3" json:"practice,omitempty"`                          // 练习币
}

func (x *PbBalance) Reset() {
	*x = PbBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisbalance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbBalance) ProtoMessage() {}

func (x *PbBalance) ProtoReflect() protoreflect.Message {
	mi := &file_redisbalance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbBalance.ProtoReflect.Descriptor instead.
func (*PbBalance) Descriptor() ([]byte, []int) {
	return file_redisbalance_proto_rawDescGZIP(), []int{1}
}

func (x *PbBalance) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PbBalance) GetBalanceWins() int32 {
	if x != nil {
		return x.BalanceWins
	}
	return 0
}

func (x *PbBalance) GetPractice() int32 {
	if x != nil {
		return x.Practice
	}
	return 0
}

// redis中存储结构
type PbRedisAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint32     `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DBBalance  *PbBalance `protobuf:"bytes,2,opt,name=DB_balance,json=DBBalance,proto3" json:"DB_balance,omitempty"`    // 数据库中同步过来的数据
	MEMBalance *PbBalance `protobuf:"bytes,3,opt,name=MEM_balance,json=MEMBalance,proto3" json:"MEM_balance,omitempty"` // 内存中，没有同步到数据库中的数据
}

func (x *PbRedisAccount) Reset() {
	*x = PbRedisAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisbalance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PbRedisAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbRedisAccount) ProtoMessage() {}

func (x *PbRedisAccount) ProtoReflect() protoreflect.Message {
	mi := &file_redisbalance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbRedisAccount.ProtoReflect.Descriptor instead.
func (*PbRedisAccount) Descriptor() ([]byte, []int) {
	return file_redisbalance_proto_rawDescGZIP(), []int{2}
}

func (x *PbRedisAccount) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PbRedisAccount) GetDBBalance() *PbBalance {
	if x != nil {
		return x.DBBalance
	}
	return nil
}

func (x *PbRedisAccount) GetMEMBalance() *PbBalance {
	if x != nil {
		return x.MEMBalance
	}
	return nil
}

// 通用请求
type CommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CommonReq) Reset() {
	*x = CommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisbalance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonReq) ProtoMessage() {}

func (x *CommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_redisbalance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonReq.ProtoReflect.Descriptor instead.
func (*CommonReq) Descriptor() ([]byte, []int) {
	return file_redisbalance_proto_rawDescGZIP(), []int{3}
}

func (x *CommonReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 通用返回
type CommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisbalance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_redisbalance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_redisbalance_proto_rawDescGZIP(), []int{4}
}

func (x *CommonResp) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 获取用户余额
type GetBalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      uint32     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	UserId      uint32     `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserBalance *PbBalance `protobuf:"bytes,3,opt,name=user_balance,json=userBalance,proto3" json:"user_balance,omitempty"`
}

func (x *GetBalanceResp) Reset() {
	*x = GetBalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisbalance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResp) ProtoMessage() {}

func (x *GetBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_redisbalance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResp.ProtoReflect.Descriptor instead.
func (*GetBalanceResp) Descriptor() ([]byte, []int) {
	return file_redisbalance_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResp) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *GetBalanceResp) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBalanceResp) GetUserBalance() *PbBalance {
	if x != nil {
		return x.UserBalance
	}
	return nil
}

// 请求更新
type UpdateBalanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        uint32     `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpdateBalance *PbBalance `protobuf:"bytes,2,opt,name=update_balance,json=updateBalance,proto3" json:"update_balance,omitempty"`
}

func (x *UpdateBalanceReq) Reset() {
	*x = UpdateBalanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redisbalance_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceReq) ProtoMessage() {}

func (x *UpdateBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_redisbalance_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceReq.ProtoReflect.Descriptor instead.
func (*UpdateBalanceReq) Descriptor() ([]byte, []int) {
	return file_redisbalance_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBalanceReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateBalanceReq) GetUpdateBalance() *PbBalance {
	if x != nil {
		return x.UpdateBalance
	}
	return nil
}

var File_redisbalance_proto protoreflect.FileDescriptor

var file_redisbalance_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x65, 0x64, 0x69, 0x73, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6f, 0x6c, 0x77, 0x69,
	0x6e, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x08, 0x70, 0x62, 0x5f, 0x62,
	0x6f, 0x6e, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x6f, 0x6e, 0x75, 0x73,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x6f, 0x6e,
	0x75, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x65, 0x0a, 0x0a, 0x70, 0x62, 0x5f, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x57, 0x69,
	0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x65, 0x22, 0xab,
	0x01, 0x0a, 0x10, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0a,
	0x44, 0x42, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6f, 0x6c, 0x77, 0x69, 0x6e, 0x38, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x09, 0x44, 0x42, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x4d,
	0x45, 0x4d, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6f, 0x6c, 0x77, 0x69, 0x6e, 0x38, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x0a, 0x4d, 0x45, 0x4d, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x24, 0x0a, 0x09,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x24, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x0c,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6f, 0x6c, 0x77, 0x69, 0x6e,
	0x38, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22,
	0x72, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x0e,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6f, 0x6c, 0x77,
	0x69, 0x6e, 0x38, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x2a, 0xba, 0x01, 0x0a, 0x0a, 0x42, 0x41, 0x5f, 0x41, 0x50, 0x49, 0x5f, 0x43,
	0x4d, 0x44, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x41, 0x5f, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x5f, 0x43, 0x4d, 0x44,
	0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x5f, 0x43, 0x4d,
	0x44, 0x5f, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x42, 0x41, 0x5f, 0x43,
	0x4d, 0x44, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x52,
	0x45, 0x51, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x42, 0x41, 0x5f, 0x43, 0x4d, 0x44, 0x5f, 0x47,
	0x45, 0x54, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10,
	0x04, 0x12, 0x1d, 0x0a, 0x19, 0x42, 0x41, 0x5f, 0x43, 0x4d, 0x44, 0x5f, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x05,
	0x12, 0x1e, 0x0a, 0x1a, 0x42, 0x41, 0x5f, 0x43, 0x4d, 0x44, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x06,
	0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6f, 0x6c, 0x77, 0x69,
	0x6e, 0x38, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redisbalance_proto_rawDescOnce sync.Once
	file_redisbalance_proto_rawDescData = file_redisbalance_proto_rawDesc
)

func file_redisbalance_proto_rawDescGZIP() []byte {
	file_redisbalance_proto_rawDescOnce.Do(func() {
		file_redisbalance_proto_rawDescData = protoimpl.X.CompressGZIP(file_redisbalance_proto_rawDescData)
	})
	return file_redisbalance_proto_rawDescData
}

var file_redisbalance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redisbalance_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_redisbalance_proto_goTypes = []interface{}{
	(BA_API_CMD)(0),          // 0: com.coolwin8.proto.BA_API_CMD
	(*PbBonus)(nil),          // 1: com.coolwin8.proto.pb_bonus
	(*PbBalance)(nil),        // 2: com.coolwin8.proto.pb_balance
	(*PbRedisAccount)(nil),   // 3: com.coolwin8.proto.pb_redis_account
	(*CommonReq)(nil),        // 4: com.coolwin8.proto.CommonReq
	(*CommonResp)(nil),       // 5: com.coolwin8.proto.CommonResp
	(*GetBalanceResp)(nil),   // 6: com.coolwin8.proto.GetBalanceResp
	(*UpdateBalanceReq)(nil), // 7: com.coolwin8.proto.UpdateBalanceReq
}
var file_redisbalance_proto_depIdxs = []int32{
	2, // 0: com.coolwin8.proto.pb_redis_account.DB_balance:type_name -> com.coolwin8.proto.pb_balance
	2, // 1: com.coolwin8.proto.pb_redis_account.MEM_balance:type_name -> com.coolwin8.proto.pb_balance
	2, // 2: com.coolwin8.proto.GetBalanceResp.user_balance:type_name -> com.coolwin8.proto.pb_balance
	2, // 3: com.coolwin8.proto.UpdateBalanceReq.update_balance:type_name -> com.coolwin8.proto.pb_balance
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_redisbalance_proto_init() }
func file_redisbalance_proto_init() {
	if File_redisbalance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redisbalance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbBonus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redisbalance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redisbalance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PbRedisAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redisbalance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redisbalance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redisbalance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redisbalance_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBalanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redisbalance_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redisbalance_proto_goTypes,
		DependencyIndexes: file_redisbalance_proto_depIdxs,
		EnumInfos:         file_redisbalance_proto_enumTypes,
		MessageInfos:      file_redisbalance_proto_msgTypes,
	}.Build()
	File_redisbalance_proto = out.File
	file_redisbalance_proto_rawDesc = nil
	file_redisbalance_proto_goTypes = nil
	file_redisbalance_proto_depIdxs = nil
}
