// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: horseracing.proto

package horseracing

import (
	platform "./com/cw/chess/platform"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//**********************************AB游戏服务端和服务端通信定义开始********************************
type Horseracing_S_Cmd int32

const (
	Horseracing_S_Cmd_CMD_S_INVALID                Horseracing_S_Cmd = 0
	Horseracing_S_Cmd_CMD_S_PING                   Horseracing_S_Cmd = 1
	Horseracing_S_Cmd_CMD_S_PONG                   Horseracing_S_Cmd = 2
	Horseracing_S_Cmd_CMD_S_HORSERACING_ENTER_REQ  Horseracing_S_Cmd = 3 // 匹配成功通知ab服务准备开始：MSG_S_HORSERACING_ENTER_REQ
	Horseracing_S_Cmd_CMD_S_HORSERACING_ENTER_RESP Horseracing_S_Cmd = 4 // 匹配成功通知ab服务准备开始返回：MSG_S_HORSERACING_ENTER_RESP
)

// Enum value maps for Horseracing_S_Cmd.
var (
	Horseracing_S_Cmd_name = map[int32]string{
		0: "CMD_S_INVALID",
		1: "CMD_S_PING",
		2: "CMD_S_PONG",
		3: "CMD_S_HORSERACING_ENTER_REQ",
		4: "CMD_S_HORSERACING_ENTER_RESP",
	}
	Horseracing_S_Cmd_value = map[string]int32{
		"CMD_S_INVALID":                0,
		"CMD_S_PING":                   1,
		"CMD_S_PONG":                   2,
		"CMD_S_HORSERACING_ENTER_REQ":  3,
		"CMD_S_HORSERACING_ENTER_RESP": 4,
	}
)

func (x Horseracing_S_Cmd) Enum() *Horseracing_S_Cmd {
	p := new(Horseracing_S_Cmd)
	*p = x
	return p
}

func (x Horseracing_S_Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Horseracing_S_Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_horseracing_proto_enumTypes[0].Descriptor()
}

func (Horseracing_S_Cmd) Type() protoreflect.EnumType {
	return &file_horseracing_proto_enumTypes[0]
}

func (x Horseracing_S_Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Horseracing_S_Cmd.Descriptor instead.
func (Horseracing_S_Cmd) EnumDescriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{0}
}

//**********************************AB游戏客户端和服务端通信定义开始********************************
type HORSERACING_C_Cmd int32

const (
	HORSERACING_C_Cmd_CMD_C_INVALID               HORSERACING_C_Cmd = 0
	HORSERACING_C_Cmd_CMD_C_GET_TABLE_STATUS_REQ  HORSERACING_C_Cmd = 1 // 请求获取游戏数据，此协议应该在客户端资源加载完成后请求（通常为刚进游戏，比如匹配成功/断线重连）MSG_C_COMMON_REQ
	HORSERACING_C_Cmd_CMD_C_GET_TABLE_STATUS_RESP HORSERACING_C_Cmd = 2 // 回复：MSG_C_GET_TABLE_STATUS_RESP
	// 以下逻辑会在牌局之间循环
	HORSERACING_C_Cmd_CMD_C_GAME_READY_3_REQ          HORSERACING_C_Cmd = 5  // 无意义
	HORSERACING_C_Cmd_CMD_C_GAME_READY_3_RESP         HORSERACING_C_Cmd = 6  // 通知客户端N秒后开始：MSG_C_GAME_READY_3_RESP
	HORSERACING_C_Cmd_CMD_C_GAME_ODDS_REQ             HORSERACING_C_Cmd = 7  // 无意义
	HORSERACING_C_Cmd_CMD_C_GAME_ODDS_RESP            HORSERACING_C_Cmd = 8  // 通知客户端赔率：MSG_C_GAME_ODDS_RESP，另外此协议代表新的一局开始
	HORSERACING_C_Cmd_CMD_C_GAME_NOTICE_REQ           HORSERACING_C_Cmd = 9  // 无意义
	HORSERACING_C_Cmd_CMD_C_GAME_NOTICE_RESP          HORSERACING_C_Cmd = 10 // 下注开始：MSG_C_GAME_NOTICE_RESP，
	HORSERACING_C_Cmd_CMD_C_GAME_RACING_REQ           HORSERACING_C_Cmd = 11 // 无意义
	HORSERACING_C_Cmd_CMD_C_GAME_RACING_RESP          HORSERACING_C_Cmd = 12 // 发牌：MSG_C_C_GAME_RACING_RESP，收到此协议代表下注停止，并且播放动画（目前为8秒）
	HORSERACING_C_Cmd_CMD_C_GAME_SETTLE_REQ           HORSERACING_C_Cmd = 13 // 无意义
	HORSERACING_C_Cmd_CMD_C_GAME_SETTLE_RESP          HORSERACING_C_Cmd = 14 // 结算：MSG_C_GAME_SETTLE_RESP，收到此协议后，3秒内要发继续包
	HORSERACING_C_Cmd_CMD_C_GAME_USER_CONTINUE_3_REQ  HORSERACING_C_Cmd = 17 // 客户端局没有下注执行退出或者继续：MSG_C_GAME_USER_CONTINUE_3_RESP
	HORSERACING_C_Cmd_CMD_C_GAME_USER_CONTINUE_3_RESP HORSERACING_C_Cmd = 18 // 无意义：客户端如果退出，自行退出，如果继续，发送完就好了
	HORSERACING_C_Cmd_CMD_C_USER_BET_REQ              HORSERACING_C_Cmd = 30 // 用户请求下注：MSG_C_USER_BET_REQ
	HORSERACING_C_Cmd_CMD_C_USER_BET_RESP             HORSERACING_C_Cmd = 31 // 用户请求下注回复：MSG_C_USER_BET_RESP
	HORSERACING_C_Cmd_CMD_C_USER_CONTINUE_REQ         HORSERACING_C_Cmd = 32 // 用户请求继续：MSG_C_USER_CONTINUE_REQ
	HORSERACING_C_Cmd_CMD_C_USER_CONTINUE_RESP        HORSERACING_C_Cmd = 33 // 用户请求继续：MSG_C_USER_CONTINUE_RESP
	HORSERACING_C_Cmd_CMD_C_USER_BET_OTHER_REQ        HORSERACING_C_Cmd = 34 // 无意义
	HORSERACING_C_Cmd_CMD_C_USER_BET_OTHER_RESP       HORSERACING_C_Cmd = 35 // 其他用户下注广播：MSG_C_USER_BET_OTHER_RESP
)

// Enum value maps for HORSERACING_C_Cmd.
var (
	HORSERACING_C_Cmd_name = map[int32]string{
		0:  "CMD_C_INVALID",
		1:  "CMD_C_GET_TABLE_STATUS_REQ",
		2:  "CMD_C_GET_TABLE_STATUS_RESP",
		5:  "CMD_C_GAME_READY_3_REQ",
		6:  "CMD_C_GAME_READY_3_RESP",
		7:  "CMD_C_GAME_ODDS_REQ",
		8:  "CMD_C_GAME_ODDS_RESP",
		9:  "CMD_C_GAME_NOTICE_REQ",
		10: "CMD_C_GAME_NOTICE_RESP",
		11: "CMD_C_GAME_RACING_REQ",
		12: "CMD_C_GAME_RACING_RESP",
		13: "CMD_C_GAME_SETTLE_REQ",
		14: "CMD_C_GAME_SETTLE_RESP",
		17: "CMD_C_GAME_USER_CONTINUE_3_REQ",
		18: "CMD_C_GAME_USER_CONTINUE_3_RESP",
		30: "CMD_C_USER_BET_REQ",
		31: "CMD_C_USER_BET_RESP",
		32: "CMD_C_USER_CONTINUE_REQ",
		33: "CMD_C_USER_CONTINUE_RESP",
		34: "CMD_C_USER_BET_OTHER_REQ",
		35: "CMD_C_USER_BET_OTHER_RESP",
	}
	HORSERACING_C_Cmd_value = map[string]int32{
		"CMD_C_INVALID":                   0,
		"CMD_C_GET_TABLE_STATUS_REQ":      1,
		"CMD_C_GET_TABLE_STATUS_RESP":     2,
		"CMD_C_GAME_READY_3_REQ":          5,
		"CMD_C_GAME_READY_3_RESP":         6,
		"CMD_C_GAME_ODDS_REQ":             7,
		"CMD_C_GAME_ODDS_RESP":            8,
		"CMD_C_GAME_NOTICE_REQ":           9,
		"CMD_C_GAME_NOTICE_RESP":          10,
		"CMD_C_GAME_RACING_REQ":           11,
		"CMD_C_GAME_RACING_RESP":          12,
		"CMD_C_GAME_SETTLE_REQ":           13,
		"CMD_C_GAME_SETTLE_RESP":          14,
		"CMD_C_GAME_USER_CONTINUE_3_REQ":  17,
		"CMD_C_GAME_USER_CONTINUE_3_RESP": 18,
		"CMD_C_USER_BET_REQ":              30,
		"CMD_C_USER_BET_RESP":             31,
		"CMD_C_USER_CONTINUE_REQ":         32,
		"CMD_C_USER_CONTINUE_RESP":        33,
		"CMD_C_USER_BET_OTHER_REQ":        34,
		"CMD_C_USER_BET_OTHER_RESP":       35,
	}
)

func (x HORSERACING_C_Cmd) Enum() *HORSERACING_C_Cmd {
	p := new(HORSERACING_C_Cmd)
	*p = x
	return p
}

func (x HORSERACING_C_Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HORSERACING_C_Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_horseracing_proto_enumTypes[1].Descriptor()
}

func (HORSERACING_C_Cmd) Type() protoreflect.EnumType {
	return &file_horseracing_proto_enumTypes[1]
}

func (x HORSERACING_C_Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HORSERACING_C_Cmd.Descriptor instead.
func (HORSERACING_C_Cmd) EnumDescriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{1}
}

// 定义游戏阶段
type GamePhase int32

const (
	GamePhase_PHS_INVALID       GamePhase = 0 // 无效
	GamePhase_PHS_Match_Ready   GamePhase = 1 // 准备阶段
	GamePhase_PHS_Game_OddsInfo GamePhase = 2 // 赛马下注信息阶段
	GamePhase_PHS_Gaming_Bet    GamePhase = 3 // 下注阶段
	GamePhase_PHS_Gaming_Racing GamePhase = 4 // 赛马阶段
	GamePhase_PHS_Game_Settle   GamePhase = 5 // 结算
	GamePhase_PHS_Game_Continue GamePhase = 6 // 用户确认继续阶段：服务器5秒等待，否则会把没有准备的用户踢出
)

// Enum value maps for GamePhase.
var (
	GamePhase_name = map[int32]string{
		0: "PHS_INVALID",
		1: "PHS_Match_Ready",
		2: "PHS_Game_OddsInfo",
		3: "PHS_Gaming_Bet",
		4: "PHS_Gaming_Racing",
		5: "PHS_Game_Settle",
		6: "PHS_Game_Continue",
	}
	GamePhase_value = map[string]int32{
		"PHS_INVALID":       0,
		"PHS_Match_Ready":   1,
		"PHS_Game_OddsInfo": 2,
		"PHS_Gaming_Bet":    3,
		"PHS_Gaming_Racing": 4,
		"PHS_Game_Settle":   5,
		"PHS_Game_Continue": 6,
	}
)

func (x GamePhase) Enum() *GamePhase {
	p := new(GamePhase)
	*p = x
	return p
}

func (x GamePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_horseracing_proto_enumTypes[2].Descriptor()
}

func (GamePhase) Type() protoreflect.EnumType {
	return &file_horseracing_proto_enumTypes[2]
}

func (x GamePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamePhase.Descriptor instead.
func (GamePhase) EnumDescriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{2}
}

// 这个是匹配服务器告诉AB服务器的请求
type MSG_S_HORSERACING_ENTER_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level uint32             `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Users *platform.GameUser `protobuf:"bytes,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *MSG_S_HORSERACING_ENTER_REQ) Reset() {
	*x = MSG_S_HORSERACING_ENTER_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_S_HORSERACING_ENTER_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_S_HORSERACING_ENTER_REQ) ProtoMessage() {}

func (x *MSG_S_HORSERACING_ENTER_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_S_HORSERACING_ENTER_REQ.ProtoReflect.Descriptor instead.
func (*MSG_S_HORSERACING_ENTER_REQ) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{0}
}

func (x *MSG_S_HORSERACING_ENTER_REQ) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MSG_S_HORSERACING_ENTER_REQ) GetUsers() *platform.GameUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// 这个是匹配服务器收到AB服务器的回复
type MSG_S_HORSERACING_ENTER_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`                  // 0：成功；
	TableId uint32 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"` // table_id：因为一个服务上有很多个桌子以服务多个用户，这里分配好后就告诉匹配服务，匹配服务再把这个tableid和本服务的id告诉客户端
}

func (x *MSG_S_HORSERACING_ENTER_RESP) Reset() {
	*x = MSG_S_HORSERACING_ENTER_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_S_HORSERACING_ENTER_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_S_HORSERACING_ENTER_RESP) ProtoMessage() {}

func (x *MSG_S_HORSERACING_ENTER_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_S_HORSERACING_ENTER_RESP.ProtoReflect.Descriptor instead.
func (*MSG_S_HORSERACING_ENTER_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{1}
}

func (x *MSG_S_HORSERACING_ENTER_RESP) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *MSG_S_HORSERACING_ENTER_RESP) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

// 通用客户端请求
type MSG_C_COMMON_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId uint32 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
}

func (x *MSG_C_COMMON_REQ) Reset() {
	*x = MSG_C_COMMON_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_COMMON_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_COMMON_REQ) ProtoMessage() {}

func (x *MSG_C_COMMON_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_COMMON_REQ.ProtoReflect.Descriptor instead.
func (*MSG_C_COMMON_REQ) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{2}
}

func (x *MSG_C_COMMON_REQ) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

// 通用服务端返回
type MSG_C_COMMON_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId uint32 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Result  uint32 `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"` // 0：正常
}

func (x *MSG_C_COMMON_RESP) Reset() {
	*x = MSG_C_COMMON_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_COMMON_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_COMMON_RESP) ProtoMessage() {}

func (x *MSG_C_COMMON_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_COMMON_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_COMMON_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{3}
}

func (x *MSG_C_COMMON_RESP) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *MSG_C_COMMON_RESP) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 注：后续所有协议全部采用“tableid+子结构”形式，包括请求和回复
type TableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId uint32 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TableData) Reset() {
	*x = TableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableData) ProtoMessage() {}

func (x *TableData) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableData.ProtoReflect.Descriptor instead.
func (*TableData) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{4}
}

func (x *TableData) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *TableData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Odds_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OIndex uint32 `protobuf:"varint,1,opt,name=o_index,json=oIndex,proto3" json:"o_index,omitempty"` // 位置1、2、3、4、5、6
	OOdds  uint32 `protobuf:"varint,2,opt,name=o_odds,json=oOdds,proto3" json:"o_odds,omitempty"`    // 赔率，百分制，例如570，表示5.7倍
	//以下字段客户端应该不需要使用，服务端计算使用
	OExpectedPer uint32 `protobuf:"varint,3,opt,name=o_expected_per,json=oExpectedPer,proto3" json:"o_expected_per,omitempty"` // 胜利概率，万分制，实际此值是o_expected_per*o_odds=o_expected_value，这里先算好，实际上是先确认此值（750-3500），再确认o_odds
}

func (x *Odds_Info) Reset() {
	*x = Odds_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Odds_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Odds_Info) ProtoMessage() {}

func (x *Odds_Info) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Odds_Info.ProtoReflect.Descriptor instead.
func (*Odds_Info) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{5}
}

func (x *Odds_Info) GetOIndex() uint32 {
	if x != nil {
		return x.OIndex
	}
	return 0
}

func (x *Odds_Info) GetOOdds() uint32 {
	if x != nil {
		return x.OOdds
	}
	return 0
}

func (x *Odds_Info) GetOExpectedPer() uint32 {
	if x != nil {
		return x.OExpectedPer
	}
	return 0
}

type Bet_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C_1 uint32 `protobuf:"varint,1,opt,name=C_1,json=C1,proto3" json:"C_1,omitempty"`
	C_2 uint32 `protobuf:"varint,2,opt,name=C_2,json=C2,proto3" json:"C_2,omitempty"`
	C_3 uint32 `protobuf:"varint,3,opt,name=C_3,json=C3,proto3" json:"C_3,omitempty"`
	C_4 uint32 `protobuf:"varint,4,opt,name=C_4,json=C4,proto3" json:"C_4,omitempty"`
	C_5 uint32 `protobuf:"varint,5,opt,name=C_5,json=C5,proto3" json:"C_5,omitempty"`
	C_6 uint32 `protobuf:"varint,6,opt,name=C_6,json=C6,proto3" json:"C_6,omitempty"`
}

func (x *Bet_Info) Reset() {
	*x = Bet_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bet_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet_Info) ProtoMessage() {}

func (x *Bet_Info) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet_Info.ProtoReflect.Descriptor instead.
func (*Bet_Info) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{6}
}

func (x *Bet_Info) GetC_1() uint32 {
	if x != nil {
		return x.C_1
	}
	return 0
}

func (x *Bet_Info) GetC_2() uint32 {
	if x != nil {
		return x.C_2
	}
	return 0
}

func (x *Bet_Info) GetC_3() uint32 {
	if x != nil {
		return x.C_3
	}
	return 0
}

func (x *Bet_Info) GetC_4() uint32 {
	if x != nil {
		return x.C_4
	}
	return 0
}

func (x *Bet_Info) GetC_5() uint32 {
	if x != nil {
		return x.C_5
	}
	return 0
}

func (x *Bet_Info) GetC_6() uint32 {
	if x != nil {
		return x.C_6
	}
	return 0
}

type MSG_C_GET_TABLE_STATUS_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LevelDesc   *platform.HorseracingDesc `protobuf:"bytes,1,opt,name=level_desc,json=levelDesc,proto3" json:"level_desc,omitempty"`
	ChipsValue  []uint32                  `protobuf:"varint,2,rep,packed,name=chips_value,json=chipsValue,proto3" json:"chips_value,omitempty"`                               // 下注5个级别的数值：等于bet_min的1/5/10/20/100倍，这里已经是算好的，例如20底分，那么值是20/100/200/400/2000
	GamePhase   GamePhase                 `protobuf:"varint,3,opt,name=game_phase,json=gamePhase,proto3,enum=com.cw.chess.horseracing.GamePhase" json:"game_phase,omitempty"` // 游戏阶段
	PlayersSize uint32                    `protobuf:"varint,4,opt,name=players_size,json=playersSize,proto3" json:"players_size,omitempty"`                                   // 用户数量
	SelfBet     *Bet_Info                 `protobuf:"bytes,5,opt,name=self_bet,json=selfBet,proto3" json:"self_bet,omitempty"`                                                // 自己下注
	AllBet      *Bet_Info                 `protobuf:"bytes,6,opt,name=all_bet,json=allBet,proto3" json:"all_bet,omitempty"`                                                   // 所有用户下注
	Odd_1       *Odds_Info                `protobuf:"bytes,7,opt,name=odd_1,json=odd1,proto3" json:"odd_1,omitempty"`                                                         // 第1个位置的赔率信息，以下雷同
	Odd_2       *Odds_Info                `protobuf:"bytes,8,opt,name=odd_2,json=odd2,proto3" json:"odd_2,omitempty"`
	Odd_3       *Odds_Info                `protobuf:"bytes,9,opt,name=odd_3,json=odd3,proto3" json:"odd_3,omitempty"`
	Odd_4       *Odds_Info                `protobuf:"bytes,10,opt,name=odd_4,json=odd4,proto3" json:"odd_4,omitempty"`
	Odd_5       *Odds_Info                `protobuf:"bytes,11,opt,name=odd_5,json=odd5,proto3" json:"odd_5,omitempty"`
	Odd_6       *Odds_Info                `protobuf:"bytes,12,opt,name=odd_6,json=odd6,proto3" json:"odd_6,omitempty"`
	Bingos      []uint32                  `protobuf:"varint,13,rep,packed,name=bingos,proto3" json:"bingos,omitempty"`                  // 历史记录
	BetType     []uint32                  `protobuf:"varint,14,rep,packed,name=bet_type,json=betType,proto3" json:"bet_type,omitempty"` // 下注的种类，例如10、50、100、200、1000
	GameId      string                    `protobuf:"bytes,15,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) Reset() {
	*x = MSG_C_GET_TABLE_STATUS_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_GET_TABLE_STATUS_RESP) ProtoMessage() {}

func (x *MSG_C_GET_TABLE_STATUS_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_GET_TABLE_STATUS_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_GET_TABLE_STATUS_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{7}
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetLevelDesc() *platform.HorseracingDesc {
	if x != nil {
		return x.LevelDesc
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetChipsValue() []uint32 {
	if x != nil {
		return x.ChipsValue
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetGamePhase() GamePhase {
	if x != nil {
		return x.GamePhase
	}
	return GamePhase_PHS_INVALID
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetPlayersSize() uint32 {
	if x != nil {
		return x.PlayersSize
	}
	return 0
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetSelfBet() *Bet_Info {
	if x != nil {
		return x.SelfBet
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetAllBet() *Bet_Info {
	if x != nil {
		return x.AllBet
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetOdd_1() *Odds_Info {
	if x != nil {
		return x.Odd_1
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetOdd_2() *Odds_Info {
	if x != nil {
		return x.Odd_2
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetOdd_3() *Odds_Info {
	if x != nil {
		return x.Odd_3
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetOdd_4() *Odds_Info {
	if x != nil {
		return x.Odd_4
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetOdd_5() *Odds_Info {
	if x != nil {
		return x.Odd_5
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetOdd_6() *Odds_Info {
	if x != nil {
		return x.Odd_6
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetBingos() []uint32 {
	if x != nil {
		return x.Bingos
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetBetType() []uint32 {
	if x != nil {
		return x.BetType
	}
	return nil
}

func (x *MSG_C_GET_TABLE_STATUS_RESP) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type MSG_C_GAME_READY_3_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times uint32 `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"` // 多久后开始
}

func (x *MSG_C_GAME_READY_3_RESP) Reset() {
	*x = MSG_C_GAME_READY_3_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_GAME_READY_3_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_GAME_READY_3_RESP) ProtoMessage() {}

func (x *MSG_C_GAME_READY_3_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_GAME_READY_3_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_GAME_READY_3_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{8}
}

func (x *MSG_C_GAME_READY_3_RESP) GetTimes() uint32 {
	if x != nil {
		return x.Times
	}
	return 0
}

type MSG_C_GAME_ODDS_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string       `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // 牌局id
	Odds   []*Odds_Info `protobuf:"bytes,2,rep,name=odds,proto3" json:"odds,omitempty"`
}

func (x *MSG_C_GAME_ODDS_RESP) Reset() {
	*x = MSG_C_GAME_ODDS_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_GAME_ODDS_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_GAME_ODDS_RESP) ProtoMessage() {}

func (x *MSG_C_GAME_ODDS_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_GAME_ODDS_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_GAME_ODDS_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{9}
}

func (x *MSG_C_GAME_ODDS_RESP) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MSG_C_GAME_ODDS_RESP) GetOdds() []*Odds_Info {
	if x != nil {
		return x.Odds
	}
	return nil
}

type MSG_C_GAME_NOTICE_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times uint32 `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"` // 下注时间
}

func (x *MSG_C_GAME_NOTICE_RESP) Reset() {
	*x = MSG_C_GAME_NOTICE_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_GAME_NOTICE_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_GAME_NOTICE_RESP) ProtoMessage() {}

func (x *MSG_C_GAME_NOTICE_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_GAME_NOTICE_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_GAME_NOTICE_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{10}
}

func (x *MSG_C_GAME_NOTICE_RESP) GetTimes() uint32 {
	if x != nil {
		return x.Times
	}
	return 0
}

type MSG_C_C_GAME_RACING_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinIndex     uint32 `protobuf:"varint,1,opt,name=win_index,json=winIndex,proto3" json:"win_index,omitempty"`             // 胜利编号，例如2
	P_1          uint32 `protobuf:"varint,2,opt,name=p_1,json=p1,proto3" json:"p_1,omitempty"`                               // 第1匹马的位置，例如3
	P_2          uint32 `protobuf:"varint,3,opt,name=p_2,json=p2,proto3" json:"p_2,omitempty"`                               // 第2匹马的位置，例如1
	P_3          uint32 `protobuf:"varint,4,opt,name=p_3,json=p3,proto3" json:"p_3,omitempty"`                               // 第3匹马的位置，例如5
	P_4          uint32 `protobuf:"varint,5,opt,name=p_4,json=p4,proto3" json:"p_4,omitempty"`                               // 第4匹马的位置，例如6
	P_5          uint32 `protobuf:"varint,6,opt,name=p_5,json=p5,proto3" json:"p_5,omitempty"`                               // 第5匹马的位置，例如4
	P_6          uint32 `protobuf:"varint,7,opt,name=p_6,json=p6,proto3" json:"p_6,omitempty"`                               // 第6匹马的位置，例如2
	BingoCurreny uint32 `protobuf:"varint,8,opt,name=bingo_curreny,json=bingoCurreny,proto3" json:"bingo_curreny,omitempty"` // 显示用户买中的区域的赢的钱（注：这里只显示，不结算，结算数据还是在结算中）
}

func (x *MSG_C_C_GAME_RACING_RESP) Reset() {
	*x = MSG_C_C_GAME_RACING_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_C_GAME_RACING_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_C_GAME_RACING_RESP) ProtoMessage() {}

func (x *MSG_C_C_GAME_RACING_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_C_GAME_RACING_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_C_GAME_RACING_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{11}
}

func (x *MSG_C_C_GAME_RACING_RESP) GetWinIndex() uint32 {
	if x != nil {
		return x.WinIndex
	}
	return 0
}

func (x *MSG_C_C_GAME_RACING_RESP) GetP_1() uint32 {
	if x != nil {
		return x.P_1
	}
	return 0
}

func (x *MSG_C_C_GAME_RACING_RESP) GetP_2() uint32 {
	if x != nil {
		return x.P_2
	}
	return 0
}

func (x *MSG_C_C_GAME_RACING_RESP) GetP_3() uint32 {
	if x != nil {
		return x.P_3
	}
	return 0
}

func (x *MSG_C_C_GAME_RACING_RESP) GetP_4() uint32 {
	if x != nil {
		return x.P_4
	}
	return 0
}

func (x *MSG_C_C_GAME_RACING_RESP) GetP_5() uint32 {
	if x != nil {
		return x.P_5
	}
	return 0
}

func (x *MSG_C_C_GAME_RACING_RESP) GetP_6() uint32 {
	if x != nil {
		return x.P_6
	}
	return 0
}

func (x *MSG_C_C_GAME_RACING_RESP) GetBingoCurreny() uint32 {
	if x != nil {
		return x.BingoCurreny
	}
	return 0
}

type MSG_C_USER_BET_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserBet *Bet_Info `protobuf:"bytes,1,opt,name=user_bet,json=userBet,proto3" json:"user_bet,omitempty"` // 用户一次下注
}

func (x *MSG_C_USER_BET_REQ) Reset() {
	*x = MSG_C_USER_BET_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_USER_BET_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_USER_BET_REQ) ProtoMessage() {}

func (x *MSG_C_USER_BET_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_USER_BET_REQ.ProtoReflect.Descriptor instead.
func (*MSG_C_USER_BET_REQ) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{12}
}

func (x *MSG_C_USER_BET_REQ) GetUserBet() *Bet_Info {
	if x != nil {
		return x.UserBet
	}
	return nil
}

type MSG_C_USER_BET_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        uint32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`                                       // 请求结果：0：成功；10：余额不够；13：用户下注超过100倍
	UserBet       *Bet_Info `protobuf:"bytes,2,opt,name=user_bet,json=userBet,proto3" json:"user_bet,omitempty"`                       // 最近一次请求结果
	UserBetAll    *Bet_Info `protobuf:"bytes,3,opt,name=user_bet_all,json=userBetAll,proto3" json:"user_bet_all,omitempty"`            // 用户全部下注
	AllUserBetAll *Bet_Info `protobuf:"bytes,4,opt,name=all_user_bet_all,json=allUserBetAll,proto3" json:"all_user_bet_all,omitempty"` // 所有用户累积下注
}

func (x *MSG_C_USER_BET_RESP) Reset() {
	*x = MSG_C_USER_BET_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_USER_BET_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_USER_BET_RESP) ProtoMessage() {}

func (x *MSG_C_USER_BET_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_USER_BET_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_USER_BET_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{13}
}

func (x *MSG_C_USER_BET_RESP) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *MSG_C_USER_BET_RESP) GetUserBet() *Bet_Info {
	if x != nil {
		return x.UserBet
	}
	return nil
}

func (x *MSG_C_USER_BET_RESP) GetUserBetAll() *Bet_Info {
	if x != nil {
		return x.UserBetAll
	}
	return nil
}

func (x *MSG_C_USER_BET_RESP) GetAllUserBetAll() *Bet_Info {
	if x != nil {
		return x.AllUserBetAll
	}
	return nil
}

type MSG_C_GAME_SETTLE_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSettle *Bet_Info `protobuf:"bytes,1,opt,name=user_settle,json=userSettle,proto3" json:"user_settle,omitempty"` // 自己的输赢，这个赢是指买中的钱
	Currency   int32     `protobuf:"varint,2,opt,name=currency,proto3" json:"currency,omitempty"`                      // 输赢的和，这个输赢是指用户所有区域赢的钱减去所有区域下注的钱的和,这个正负代表输赢
	Bingos     []uint32  `protobuf:"varint,3,rep,packed,name=bingos,proto3" json:"bingos,omitempty"`                   // 历史记录（包含本局，最后一条是最新的）
}

func (x *MSG_C_GAME_SETTLE_RESP) Reset() {
	*x = MSG_C_GAME_SETTLE_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_GAME_SETTLE_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_GAME_SETTLE_RESP) ProtoMessage() {}

func (x *MSG_C_GAME_SETTLE_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_GAME_SETTLE_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_GAME_SETTLE_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{14}
}

func (x *MSG_C_GAME_SETTLE_RESP) GetUserSettle() *Bet_Info {
	if x != nil {
		return x.UserSettle
	}
	return nil
}

func (x *MSG_C_GAME_SETTLE_RESP) GetCurrency() int32 {
	if x != nil {
		return x.Currency
	}
	return 0
}

func (x *MSG_C_GAME_SETTLE_RESP) GetBingos() []uint32 {
	if x != nil {
		return x.Bingos
	}
	return nil
}

type MSG_C_USER_CONTINUE_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BContinue uint32 `protobuf:"varint,1,opt,name=b_continue,json=bContinue,proto3" json:"b_continue,omitempty"` // 0：继续
}

func (x *MSG_C_USER_CONTINUE_REQ) Reset() {
	*x = MSG_C_USER_CONTINUE_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_USER_CONTINUE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_USER_CONTINUE_REQ) ProtoMessage() {}

func (x *MSG_C_USER_CONTINUE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_USER_CONTINUE_REQ.ProtoReflect.Descriptor instead.
func (*MSG_C_USER_CONTINUE_REQ) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{15}
}

func (x *MSG_C_USER_CONTINUE_REQ) GetBContinue() uint32 {
	if x != nil {
		return x.BContinue
	}
	return 0
}

type MSG_C_GAME_USER_CONTINUE_3_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BContinue uint32 `protobuf:"varint,1,opt,name=b_continue,json=bContinue,proto3" json:"b_continue,omitempty"` // 0：继续，1：退出
}

func (x *MSG_C_GAME_USER_CONTINUE_3_RESP) Reset() {
	*x = MSG_C_GAME_USER_CONTINUE_3_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_GAME_USER_CONTINUE_3_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_GAME_USER_CONTINUE_3_RESP) ProtoMessage() {}

func (x *MSG_C_GAME_USER_CONTINUE_3_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_GAME_USER_CONTINUE_3_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_GAME_USER_CONTINUE_3_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{16}
}

func (x *MSG_C_GAME_USER_CONTINUE_3_RESP) GetBContinue() uint32 {
	if x != nil {
		return x.BContinue
	}
	return 0
}

type MSG_C_USER_CONTINUE_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`                              // 0：成功；103：某用户余额不够；10：因为用户连续10次没有下注，所以踢出房间
	PlayersSize uint32 `protobuf:"varint,2,opt,name=players_size,json=playersSize,proto3" json:"players_size,omitempty"` // 用户数量
}

func (x *MSG_C_USER_CONTINUE_RESP) Reset() {
	*x = MSG_C_USER_CONTINUE_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_USER_CONTINUE_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_USER_CONTINUE_RESP) ProtoMessage() {}

func (x *MSG_C_USER_CONTINUE_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_USER_CONTINUE_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_USER_CONTINUE_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{17}
}

func (x *MSG_C_USER_CONTINUE_RESP) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *MSG_C_USER_CONTINUE_RESP) GetPlayersSize() uint32 {
	if x != nil {
		return x.PlayersSize
	}
	return 0
}

type MSG_C_USER_BET_OTHER_RESP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameUser      *platform.GameUser `protobuf:"bytes,1,opt,name=game_user,json=gameUser,proto3" json:"game_user,omitempty"`                    // 用户信息
	UserBet       *Bet_Info          `protobuf:"bytes,2,opt,name=user_bet,json=userBet,proto3" json:"user_bet,omitempty"`                       // 最近一次请求结果
	UserBetAll    *Bet_Info          `protobuf:"bytes,3,opt,name=user_bet_all,json=userBetAll,proto3" json:"user_bet_all,omitempty"`            // 单个用户累计下注
	AllUserBetAll *Bet_Info          `protobuf:"bytes,4,opt,name=all_user_bet_all,json=allUserBetAll,proto3" json:"all_user_bet_all,omitempty"` // 所有用户累积下注
}

func (x *MSG_C_USER_BET_OTHER_RESP) Reset() {
	*x = MSG_C_USER_BET_OTHER_RESP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_horseracing_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG_C_USER_BET_OTHER_RESP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG_C_USER_BET_OTHER_RESP) ProtoMessage() {}

func (x *MSG_C_USER_BET_OTHER_RESP) ProtoReflect() protoreflect.Message {
	mi := &file_horseracing_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG_C_USER_BET_OTHER_RESP.ProtoReflect.Descriptor instead.
func (*MSG_C_USER_BET_OTHER_RESP) Descriptor() ([]byte, []int) {
	return file_horseracing_proto_rawDescGZIP(), []int{18}
}

func (x *MSG_C_USER_BET_OTHER_RESP) GetGameUser() *platform.GameUser {
	if x != nil {
		return x.GameUser
	}
	return nil
}

func (x *MSG_C_USER_BET_OTHER_RESP) GetUserBet() *Bet_Info {
	if x != nil {
		return x.UserBet
	}
	return nil
}

func (x *MSG_C_USER_BET_OTHER_RESP) GetUserBetAll() *Bet_Info {
	if x != nil {
		return x.UserBetAll
	}
	return nil
}

func (x *MSG_C_USER_BET_OTHER_RESP) GetAllUserBetAll() *Bet_Info {
	if x != nil {
		return x.AllUserBetAll
	}
	return nil
}

var File_horseracing_proto protoreflect.FileDescriptor

var file_horseracing_proto_rawDesc = []byte{
	0x0a, 0x11, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73,
	0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x1a, 0x0e, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a,
	0x1b, 0x4d, 0x53, 0x47, 0x5f, 0x53, 0x5f, 0x48, 0x4f, 0x52, 0x53, 0x45, 0x52, 0x41, 0x43, 0x49,
	0x4e, 0x47, 0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x35, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x51, 0x0a, 0x1c, 0x4d, 0x53, 0x47,
	0x5f, 0x53, 0x5f, 0x48, 0x4f, 0x52, 0x53, 0x45, 0x52, 0x41, 0x43, 0x49, 0x4e, 0x47, 0x5f, 0x45,
	0x4e, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x10,
	0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x51,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x11, 0x4d,
	0x53, 0x47, 0x5f, 0x43, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x50,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x3a, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x61, 0x0a, 0x09, 0x4f, 0x64, 0x64, 0x73, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07,
	0x6f, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x5f, 0x6f, 0x64, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x4f, 0x64, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x0e,
	0x6f, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x6f, 0x45, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50,
	0x65, 0x72, 0x22, 0x70, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f,
	0x0a, 0x03, 0x43, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x43, 0x31, 0x12,
	0x0f, 0x0a, 0x03, 0x43, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x43, 0x32,
	0x12, 0x0f, 0x0a, 0x03, 0x43, 0x5f, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x43,
	0x33, 0x12, 0x0f, 0x0a, 0x03, 0x43, 0x5f, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x43, 0x34, 0x12, 0x0f, 0x0a, 0x03, 0x43, 0x5f, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x43, 0x35, 0x12, 0x0f, 0x0a, 0x03, 0x43, 0x5f, 0x36, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x43, 0x36, 0x22, 0x90, 0x06, 0x0a, 0x1b, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x47,
	0x45, 0x54, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x52, 0x45, 0x53, 0x50, 0x12, 0x45, 0x0a, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x73, 0x63,
	0x52, 0x09, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x68, 0x69, 0x70, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x0a, 0x63, 0x68, 0x69, 0x70, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x42, 0x0a, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e,
	0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x5f, 0x62, 0x65, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63,
	0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67,
	0x2e, 0x42, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x65, 0x6c, 0x66, 0x42,
	0x65, 0x74, 0x12, 0x3b, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x5f, 0x62, 0x65, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65,
	0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x42,
	0x65, 0x74, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x6c, 0x6c, 0x42, 0x65, 0x74, 0x12,
	0x38, 0x0a, 0x05, 0x6f, 0x64, 0x64, 0x5f, 0x31, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f,
	0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x64, 0x64, 0x73, 0x5f, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6f, 0x64, 0x64, 0x31, 0x12, 0x38, 0x0a, 0x05, 0x6f, 0x64, 0x64,
	0x5f, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63,
	0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x64, 0x64, 0x73, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6f,
	0x64, 0x64, 0x32, 0x12, 0x38, 0x0a, 0x05, 0x6f, 0x64, 0x64, 0x5f, 0x33, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73,
	0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x64,
	0x64, 0x73, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6f, 0x64, 0x64, 0x33, 0x12, 0x38, 0x0a,
	0x05, 0x6f, 0x64, 0x64, 0x5f, 0x34, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73,
	0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x64, 0x64, 0x73, 0x5f, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x6f, 0x64, 0x64, 0x34, 0x12, 0x38, 0x0a, 0x05, 0x6f, 0x64, 0x64, 0x5f, 0x35,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e,
	0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e,
	0x67, 0x2e, 0x4f, 0x64, 0x64, 0x73, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6f, 0x64, 0x64,
	0x35, 0x12, 0x38, 0x0a, 0x05, 0x6f, 0x64, 0x64, 0x5f, 0x36, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e,
	0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x64, 0x64, 0x73,
	0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6f, 0x64, 0x64, 0x36, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x69, 0x6e, 0x67, 0x6f, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x69, 0x6e,
	0x67, 0x6f, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x65, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x0e, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x17, 0x4d, 0x53, 0x47, 0x5f, 0x43,
	0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x33, 0x5f, 0x52, 0x45,
	0x53, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x68, 0x0a, 0x14, 0x4d, 0x53, 0x47, 0x5f,
	0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4f, 0x44, 0x44, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x50,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x04, 0x6f, 0x64, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77,
	0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69,
	0x6e, 0x67, 0x2e, 0x4f, 0x64, 0x64, 0x73, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6f, 0x64,
	0x64, 0x73, 0x22, 0x2e, 0x0a, 0x16, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x18, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x43, 0x5f, 0x47,
	0x41, 0x4d, 0x45, 0x5f, 0x52, 0x41, 0x43, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12,
	0x1b, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0f, 0x0a, 0x03,
	0x70, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x70, 0x31, 0x12, 0x0f, 0x0a,
	0x03, 0x70, 0x5f, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x70, 0x32, 0x12, 0x0f,
	0x0a, 0x03, 0x70, 0x5f, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x70, 0x33, 0x12,
	0x0f, 0x0a, 0x03, 0x70, 0x5f, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x70, 0x34,
	0x12, 0x0f, 0x0a, 0x03, 0x70, 0x5f, 0x35, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x70,
	0x35, 0x12, 0x0f, 0x0a, 0x03, 0x70, 0x5f, 0x36, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x70, 0x36, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x69, 0x6e, 0x67, 0x6f, 0x5f, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62, 0x69, 0x6e, 0x67, 0x6f,
	0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x79, 0x22, 0x53, 0x0a, 0x12, 0x4d, 0x53, 0x47, 0x5f, 0x43,
	0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x3d, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68,
	0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x65, 0x74, 0x5f, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x22, 0xff, 0x01, 0x0a,
	0x13, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x42, 0x45, 0x54, 0x5f,
	0x52, 0x45, 0x53, 0x50, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3d, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f,
	0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x65, 0x74, 0x5f, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x12, 0x44, 0x0a, 0x0c, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x62, 0x65, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73,
	0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x65, 0x74,
	0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x4b, 0x0a, 0x10, 0x61, 0x6c, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x65,
	0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65,
	0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0d, 0x61, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x22, 0x91,
	0x01, 0x0a, 0x16, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x45,
	0x54, 0x54, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12, 0x43, 0x0a, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f,
	0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x65, 0x74, 0x5f, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69,
	0x6e, 0x67, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x67,
	0x6f, 0x73, 0x22, 0x38, 0x0a, 0x17, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x55, 0x53, 0x45, 0x52,
	0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x1f,
	0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x33, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x22, 0x55,
	0x0a, 0x18, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e,
	0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xab, 0x02, 0x0a, 0x19, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x5f,
	0x55, 0x53, 0x45, 0x52, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x52,
	0x45, 0x53, 0x50, 0x12, 0x3c, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e,
	0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x3d, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65,
	0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x42,
	0x65, 0x74, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74,
	0x12, 0x44, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x65, 0x74, 0x5f, 0x61, 0x6c, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e,
	0x63, 0x68, 0x65, 0x73, 0x73, 0x2e, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e,
	0x67, 0x2e, 0x42, 0x65, 0x74, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x42, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x4b, 0x0a, 0x10, 0x61, 0x6c, 0x6c, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x62, 0x65, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x77, 0x2e, 0x63, 0x68, 0x65, 0x73, 0x73, 0x2e,
	0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x42, 0x65, 0x74, 0x5f,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x2a, 0x89, 0x01, 0x0a, 0x11, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63,
	0x69, 0x6e, 0x67, 0x5f, 0x53, 0x5f, 0x43, 0x6d, 0x64, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4d, 0x44,
	0x5f, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x4d, 0x44, 0x5f, 0x53, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x4d, 0x44, 0x5f, 0x53, 0x5f, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x1f, 0x0a, 0x1b,
	0x43, 0x4d, 0x44, 0x5f, 0x53, 0x5f, 0x48, 0x4f, 0x52, 0x53, 0x45, 0x52, 0x41, 0x43, 0x49, 0x4e,
	0x47, 0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x03, 0x12, 0x20, 0x0a,
	0x1c, 0x43, 0x4d, 0x44, 0x5f, 0x53, 0x5f, 0x48, 0x4f, 0x52, 0x53, 0x45, 0x52, 0x41, 0x43, 0x49,
	0x4e, 0x47, 0x5f, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x04, 0x2a,
	0xea, 0x04, 0x0a, 0x11, 0x48, 0x4f, 0x52, 0x53, 0x45, 0x52, 0x41, 0x43, 0x49, 0x4e, 0x47, 0x5f,
	0x43, 0x5f, 0x43, 0x6d, 0x64, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4d, 0x44, 0x5f,
	0x43, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4d, 0x44, 0x5f,
	0x43, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4d, 0x44,
	0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x33, 0x5f,
	0x52, 0x45, 0x51, 0x10, 0x05, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47,
	0x41, 0x4d, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x33, 0x5f, 0x52, 0x45, 0x53, 0x50,
	0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45,
	0x5f, 0x4f, 0x44, 0x44, 0x53, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x07, 0x12, 0x18, 0x0a, 0x14, 0x43,
	0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4f, 0x44, 0x44, 0x53, 0x5f, 0x52,
	0x45, 0x53, 0x50, 0x10, 0x08, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47,
	0x41, 0x4d, 0x45, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x09,
	0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4e,
	0x4f, 0x54, 0x49, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x0a, 0x12, 0x19, 0x0a, 0x15,
	0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x41, 0x43, 0x49, 0x4e,
	0x47, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0b, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x4d, 0x44, 0x5f, 0x43,
	0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x52, 0x41, 0x43, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x10, 0x0c, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d,
	0x45, 0x5f, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0d, 0x12, 0x1a,
	0x0a, 0x16, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x45, 0x54,
	0x54, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x0e, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4d,
	0x44, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x33, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x11, 0x12, 0x23,
	0x0a, 0x1f, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x33, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x10, 0x12, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x1e, 0x12, 0x17, 0x0a, 0x13, 0x43,
	0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x42, 0x45, 0x54, 0x5f, 0x52, 0x45,
	0x53, 0x50, 0x10, 0x1f, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10,
	0x20, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x21, 0x12,
	0x1c, 0x0a, 0x18, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x42, 0x45,
	0x54, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x22, 0x12, 0x1d, 0x0a,
	0x19, 0x43, 0x4d, 0x44, 0x5f, 0x43, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x42, 0x45, 0x54, 0x5f,
	0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x23, 0x2a, 0x9f, 0x01, 0x0a,
	0x09, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x48,
	0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x50,
	0x48, 0x53, 0x5f, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x50, 0x48, 0x53, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x4f, 0x64, 0x64,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x48, 0x53, 0x5f, 0x47,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x42, 0x65, 0x74, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x50,
	0x48, 0x53, 0x5f, 0x47, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x52, 0x61, 0x63, 0x69, 0x6e, 0x67,
	0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x48, 0x53, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x53,
	0x65, 0x74, 0x74, 0x6c, 0x65, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x48, 0x53, 0x5f, 0x47,
	0x61, 0x6d, 0x65, 0x5f, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x10, 0x06, 0x42, 0x1c,
	0x5a, 0x1a, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x77, 0x2f, 0x63, 0x68, 0x65, 0x73, 0x73,
	0x2f, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_horseracing_proto_rawDescOnce sync.Once
	file_horseracing_proto_rawDescData = file_horseracing_proto_rawDesc
)

func file_horseracing_proto_rawDescGZIP() []byte {
	file_horseracing_proto_rawDescOnce.Do(func() {
		file_horseracing_proto_rawDescData = protoimpl.X.CompressGZIP(file_horseracing_proto_rawDescData)
	})
	return file_horseracing_proto_rawDescData
}

var file_horseracing_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_horseracing_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_horseracing_proto_goTypes = []interface{}{
	(Horseracing_S_Cmd)(0),                  // 0: com.cw.chess.horseracing.Horseracing_S_Cmd
	(HORSERACING_C_Cmd)(0),                  // 1: com.cw.chess.horseracing.HORSERACING_C_Cmd
	(GamePhase)(0),                          // 2: com.cw.chess.horseracing.GamePhase
	(*MSG_S_HORSERACING_ENTER_REQ)(nil),     // 3: com.cw.chess.horseracing.MSG_S_HORSERACING_ENTER_REQ
	(*MSG_S_HORSERACING_ENTER_RESP)(nil),    // 4: com.cw.chess.horseracing.MSG_S_HORSERACING_ENTER_RESP
	(*MSG_C_COMMON_REQ)(nil),                // 5: com.cw.chess.horseracing.MSG_C_COMMON_REQ
	(*MSG_C_COMMON_RESP)(nil),               // 6: com.cw.chess.horseracing.MSG_C_COMMON_RESP
	(*TableData)(nil),                       // 7: com.cw.chess.horseracing.TableData
	(*Odds_Info)(nil),                       // 8: com.cw.chess.horseracing.Odds_Info
	(*Bet_Info)(nil),                        // 9: com.cw.chess.horseracing.Bet_Info
	(*MSG_C_GET_TABLE_STATUS_RESP)(nil),     // 10: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP
	(*MSG_C_GAME_READY_3_RESP)(nil),         // 11: com.cw.chess.horseracing.MSG_C_GAME_READY_3_RESP
	(*MSG_C_GAME_ODDS_RESP)(nil),            // 12: com.cw.chess.horseracing.MSG_C_GAME_ODDS_RESP
	(*MSG_C_GAME_NOTICE_RESP)(nil),          // 13: com.cw.chess.horseracing.MSG_C_GAME_NOTICE_RESP
	(*MSG_C_C_GAME_RACING_RESP)(nil),        // 14: com.cw.chess.horseracing.MSG_C_C_GAME_RACING_RESP
	(*MSG_C_USER_BET_REQ)(nil),              // 15: com.cw.chess.horseracing.MSG_C_USER_BET_REQ
	(*MSG_C_USER_BET_RESP)(nil),             // 16: com.cw.chess.horseracing.MSG_C_USER_BET_RESP
	(*MSG_C_GAME_SETTLE_RESP)(nil),          // 17: com.cw.chess.horseracing.MSG_C_GAME_SETTLE_RESP
	(*MSG_C_USER_CONTINUE_REQ)(nil),         // 18: com.cw.chess.horseracing.MSG_C_USER_CONTINUE_REQ
	(*MSG_C_GAME_USER_CONTINUE_3_RESP)(nil), // 19: com.cw.chess.horseracing.MSG_C_GAME_USER_CONTINUE_3_RESP
	(*MSG_C_USER_CONTINUE_RESP)(nil),        // 20: com.cw.chess.horseracing.MSG_C_USER_CONTINUE_RESP
	(*MSG_C_USER_BET_OTHER_RESP)(nil),       // 21: com.cw.chess.horseracing.MSG_C_USER_BET_OTHER_RESP
	(*platform.GameUser)(nil),               // 22: com.cw.chess.platform.GameUser
	(*platform.HorseracingDesc)(nil),        // 23: com.cw.chess.platform.HorseracingDesc
}
var file_horseracing_proto_depIdxs = []int32{
	22, // 0: com.cw.chess.horseracing.MSG_S_HORSERACING_ENTER_REQ.users:type_name -> com.cw.chess.platform.GameUser
	23, // 1: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.level_desc:type_name -> com.cw.chess.platform.HorseracingDesc
	2,  // 2: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.game_phase:type_name -> com.cw.chess.horseracing.GamePhase
	9,  // 3: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.self_bet:type_name -> com.cw.chess.horseracing.Bet_Info
	9,  // 4: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.all_bet:type_name -> com.cw.chess.horseracing.Bet_Info
	8,  // 5: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.odd_1:type_name -> com.cw.chess.horseracing.Odds_Info
	8,  // 6: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.odd_2:type_name -> com.cw.chess.horseracing.Odds_Info
	8,  // 7: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.odd_3:type_name -> com.cw.chess.horseracing.Odds_Info
	8,  // 8: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.odd_4:type_name -> com.cw.chess.horseracing.Odds_Info
	8,  // 9: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.odd_5:type_name -> com.cw.chess.horseracing.Odds_Info
	8,  // 10: com.cw.chess.horseracing.MSG_C_GET_TABLE_STATUS_RESP.odd_6:type_name -> com.cw.chess.horseracing.Odds_Info
	8,  // 11: com.cw.chess.horseracing.MSG_C_GAME_ODDS_RESP.odds:type_name -> com.cw.chess.horseracing.Odds_Info
	9,  // 12: com.cw.chess.horseracing.MSG_C_USER_BET_REQ.user_bet:type_name -> com.cw.chess.horseracing.Bet_Info
	9,  // 13: com.cw.chess.horseracing.MSG_C_USER_BET_RESP.user_bet:type_name -> com.cw.chess.horseracing.Bet_Info
	9,  // 14: com.cw.chess.horseracing.MSG_C_USER_BET_RESP.user_bet_all:type_name -> com.cw.chess.horseracing.Bet_Info
	9,  // 15: com.cw.chess.horseracing.MSG_C_USER_BET_RESP.all_user_bet_all:type_name -> com.cw.chess.horseracing.Bet_Info
	9,  // 16: com.cw.chess.horseracing.MSG_C_GAME_SETTLE_RESP.user_settle:type_name -> com.cw.chess.horseracing.Bet_Info
	22, // 17: com.cw.chess.horseracing.MSG_C_USER_BET_OTHER_RESP.game_user:type_name -> com.cw.chess.platform.GameUser
	9,  // 18: com.cw.chess.horseracing.MSG_C_USER_BET_OTHER_RESP.user_bet:type_name -> com.cw.chess.horseracing.Bet_Info
	9,  // 19: com.cw.chess.horseracing.MSG_C_USER_BET_OTHER_RESP.user_bet_all:type_name -> com.cw.chess.horseracing.Bet_Info
	9,  // 20: com.cw.chess.horseracing.MSG_C_USER_BET_OTHER_RESP.all_user_bet_all:type_name -> com.cw.chess.horseracing.Bet_Info
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_horseracing_proto_init() }
func file_horseracing_proto_init() {
	if File_horseracing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_horseracing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_S_HORSERACING_ENTER_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_S_HORSERACING_ENTER_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_COMMON_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_COMMON_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Odds_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bet_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_GET_TABLE_STATUS_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_GAME_READY_3_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_GAME_ODDS_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_GAME_NOTICE_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_C_GAME_RACING_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_USER_BET_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_USER_BET_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_GAME_SETTLE_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_USER_CONTINUE_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_GAME_USER_CONTINUE_3_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_USER_CONTINUE_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_horseracing_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG_C_USER_BET_OTHER_RESP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_horseracing_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_horseracing_proto_goTypes,
		DependencyIndexes: file_horseracing_proto_depIdxs,
		EnumInfos:         file_horseracing_proto_enumTypes,
		MessageInfos:      file_horseracing_proto_msgTypes,
	}.Build()
	File_horseracing_proto = out.File
	file_horseracing_proto_rawDesc = nil
	file_horseracing_proto_goTypes = nil
	file_horseracing_proto_depIdxs = nil
}
