// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: web.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsType int32

const (
	GoodsType_Goods_Invalid      GoodsType = 0 // 无效
	GoodsType_Goods_balance      GoodsType = 1 // 物品：金钱（充值分）
	GoodsType_Goods_balance_wins GoodsType = 2 // 物品：金钱（赢分）
	GoodsType_Goods_bonus        GoodsType = 3 // 物品：bonus
)

// Enum value maps for GoodsType.
var (
	GoodsType_name = map[int32]string{
		0: "Goods_Invalid",
		1: "Goods_balance",
		2: "Goods_balance_wins",
		3: "Goods_bonus",
	}
	GoodsType_value = map[string]int32{
		"Goods_Invalid":      0,
		"Goods_balance":      1,
		"Goods_balance_wins": 2,
		"Goods_bonus":        3,
	}
)

func (x GoodsType) Enum() *GoodsType {
	p := new(GoodsType)
	*p = x
	return p
}

func (x GoodsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoodsType) Descriptor() protoreflect.EnumDescriptor {
	return file_web_proto_enumTypes[0].Descriptor()
}

func (GoodsType) Type() protoreflect.EnumType {
	return &file_web_proto_enumTypes[0]
}

func (x GoodsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoodsType.Descriptor instead.
func (GoodsType) EnumDescriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{0}
}

// 更新玩家余额请求
type WebUpdateBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // 用户Id
	UpdateType   uint32   `protobuf:"varint,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`       // 更新类型，1 为充值；2 为提款；3：返回wins给用户;4:增加练习币
	Amount       uint32   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                 // 具体额度
	Serial       string   `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`                                  // 流水号
	Bonus        uint32   `protobuf:"varint,5,opt,name=bonus,proto3" json:"bonus,omitempty"`                                   // 赠送金额
	Purchase     uint32   `protobuf:"varint,6,opt,name=purchase,proto3" json:"purchase,omitempty"`                             // 类型：此类型由PHP直接到客户端，具体值的意义由PHP和客户端协定，服务器只是转发给用户（通过协议：CMD_LOBBY_USERMESSAGE_RECHARGE_REP->UserMessageRecharge）
	Value        []uint32 `protobuf:"varint,7,rep,packed,name=value,proto3" json:"value,omitempty"`                            // 值：因为我们不清除不同类型的purchase需要多少个数值，所以数值的多少由PHP和客户端自行商定
	CouponsIndex uint32   `protobuf:"varint,8,opt,name=coupons_index,json=couponsIndex,proto3" json:"coupons_index,omitempty"` // 优惠卷ID，只有在充值的情况下才需要使用，bonus字段将不再使用
}

func (x *WebUpdateBalanceRequest) Reset() {
	*x = WebUpdateBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebUpdateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebUpdateBalanceRequest) ProtoMessage() {}

func (x *WebUpdateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebUpdateBalanceRequest.ProtoReflect.Descriptor instead.
func (*WebUpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{0}
}

func (x *WebUpdateBalanceRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WebUpdateBalanceRequest) GetUpdateType() uint32 {
	if x != nil {
		return x.UpdateType
	}
	return 0
}

func (x *WebUpdateBalanceRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WebUpdateBalanceRequest) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *WebUpdateBalanceRequest) GetBonus() uint32 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

func (x *WebUpdateBalanceRequest) GetPurchase() uint32 {
	if x != nil {
		return x.Purchase
	}
	return 0
}

func (x *WebUpdateBalanceRequest) GetValue() []uint32 {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WebUpdateBalanceRequest) GetCouponsIndex() uint32 {
	if x != nil {
		return x.CouponsIndex
	}
	return 0
}

// 更新玩家余额回复
type WebUpdateBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户Id
	Result uint32 `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`               // 结果。0 为成功，1 充值失败，2 为余额不足（提款失败）
	Serial string `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`                // 流水号
}

func (x *WebUpdateBalanceResponse) Reset() {
	*x = WebUpdateBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebUpdateBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebUpdateBalanceResponse) ProtoMessage() {}

func (x *WebUpdateBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebUpdateBalanceResponse.ProtoReflect.Descriptor instead.
func (*WebUpdateBalanceResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{1}
}

func (x *WebUpdateBalanceResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WebUpdateBalanceResponse) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *WebUpdateBalanceResponse) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

// 冻结用户请求
type WebFreezePlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户Id
}

func (x *WebFreezePlayerRequest) Reset() {
	*x = WebFreezePlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebFreezePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFreezePlayerRequest) ProtoMessage() {}

func (x *WebFreezePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFreezePlayerRequest.ProtoReflect.Descriptor instead.
func (*WebFreezePlayerRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{2}
}

func (x *WebFreezePlayerRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 冻结用户返回
type WebFreezePlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WebFreezePlayerResponse) Reset() {
	*x = WebFreezePlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebFreezePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebFreezePlayerResponse) ProtoMessage() {}

func (x *WebFreezePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebFreezePlayerResponse.ProtoReflect.Descriptor instead.
func (*WebFreezePlayerResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{3}
}

// 获取桌子信息请求
type WebTableInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId uint32 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"` // 桌子Id
}

func (x *WebTableInformationRequest) Reset() {
	*x = WebTableInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebTableInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebTableInformationRequest) ProtoMessage() {}

func (x *WebTableInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebTableInformationRequest.ProtoReflect.Descriptor instead.
func (*WebTableInformationRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{4}
}

func (x *WebTableInformationRequest) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

type TablePlayerInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // 用户Id
	SeatId    uint32   `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`                 // 座位号
	HandsCard []uint32 `protobuf:"varint,3,rep,packed,name=hands_card,json=handsCard,proto3" json:"hands_card,omitempty"` // 手牌
	CardsType uint32   `protobuf:"varint,4,opt,name=cards_type,json=cardsType,proto3" json:"cards_type,omitempty"`        // 当前牌型
	Betting   uint32   `protobuf:"varint,5,opt,name=betting,proto3" json:"betting,omitempty"`                             // 下注额
}

func (x *TablePlayerInformation) Reset() {
	*x = TablePlayerInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TablePlayerInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablePlayerInformation) ProtoMessage() {}

func (x *TablePlayerInformation) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablePlayerInformation.ProtoReflect.Descriptor instead.
func (*TablePlayerInformation) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{5}
}

func (x *TablePlayerInformation) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TablePlayerInformation) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *TablePlayerInformation) GetHandsCard() []uint32 {
	if x != nil {
		return x.HandsCard
	}
	return nil
}

func (x *TablePlayerInformation) GetCardsType() uint32 {
	if x != nil {
		return x.CardsType
	}
	return 0
}

func (x *TablePlayerInformation) GetBetting() uint32 {
	if x != nil {
		return x.Betting
	}
	return 0
}

// 获取桌子信息返回
type WebTableInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId      uint32                    `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`                  // 桌子Id
	BoardCards   []uint32                  `protobuf:"varint,2,rep,packed,name=board_cards,json=boardCards,proto3" json:"board_cards,omitempty"`  // 公共牌
	ButtonSeatId uint32                    `protobuf:"varint,3,opt,name=button_seat_id,json=buttonSeatId,proto3" json:"button_seat_id,omitempty"` // button 位
	Players      []*TablePlayerInformation `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`                                  // 玩家信息
}

func (x *WebTableInformationResponse) Reset() {
	*x = WebTableInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebTableInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebTableInformationResponse) ProtoMessage() {}

func (x *WebTableInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebTableInformationResponse.ProtoReflect.Descriptor instead.
func (*WebTableInformationResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{6}
}

func (x *WebTableInformationResponse) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *WebTableInformationResponse) GetBoardCards() []uint32 {
	if x != nil {
		return x.BoardCards
	}
	return nil
}

func (x *WebTableInformationResponse) GetButtonSeatId() uint32 {
	if x != nil {
		return x.ButtonSeatId
	}
	return 0
}

func (x *WebTableInformationResponse) GetPlayers() []*TablePlayerInformation {
	if x != nil {
		return x.Players
	}
	return nil
}

// 支付回调业务（cw）
type CWPayCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID uint64 `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"` // 订单号
}

func (x *CWPayCallbackRequest) Reset() {
	*x = CWPayCallbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CWPayCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CWPayCallbackRequest) ProtoMessage() {}

func (x *CWPayCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CWPayCallbackRequest.ProtoReflect.Descriptor instead.
func (*CWPayCallbackRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{7}
}

func (x *CWPayCallbackRequest) GetOrderID() uint64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

// 支付回调业务（cw）
type CWPayCallbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 回复
}

func (x *CWPayCallbackResponse) Reset() {
	*x = CWPayCallbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CWPayCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CWPayCallbackResponse) ProtoMessage() {}

func (x *CWPayCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CWPayCallbackResponse.ProtoReflect.Descriptor instead.
func (*CWPayCallbackResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{8}
}

func (x *CWPayCallbackResponse) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type StandTexasTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskKind uint32 `protobuf:"varint,1,opt,name=task_kind,json=taskKind,proto3" json:"task_kind,omitempty"`
	// 3001：参与局（小盲0以上）
	// 3002：参与局（小盲100以上）
	// 3011：投注（小盲0以上）
	// 3012：投注（小盲100以上）
	// 3021：赢钱（小盲0以上）
	// 3022：赢钱（小盲100以上）
	Value uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // 数值
}

func (x *StandTexasTaskRequest) Reset() {
	*x = StandTexasTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandTexasTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandTexasTaskRequest) ProtoMessage() {}

func (x *StandTexasTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandTexasTaskRequest.ProtoReflect.Descriptor instead.
func (*StandTexasTaskRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{9}
}

func (x *StandTexasTaskRequest) GetTaskKind() uint32 {
	if x != nil {
		return x.TaskKind
	}
	return 0
}

func (x *StandTexasTaskRequest) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StandTexasTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StandTexasTaskResponse) Reset() {
	*x = StandTexasTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandTexasTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandTexasTaskResponse) ProtoMessage() {}

func (x *StandTexasTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandTexasTaskResponse.ProtoReflect.Descriptor instead.
func (*StandTexasTaskResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{10}
}

type SYSMessageToUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToAll     uint32 `protobuf:"varint,1,opt,name=ToAll,proto3" json:"ToAll,omitempty"`                 // 0：无意义；1：单个用户；2：全部用户
	UserId    uint32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID，只有ToAll=1的时候才有意义
	BeginTime uint32 `protobuf:"varint,3,opt,name=beginTime,proto3" json:"beginTime,omitempty"`         // 开始时间戳，以服务器时间为准，如果为0，则马上开始(目前版本只支持0)
	LastTime  uint32 `protobuf:"varint,4,opt,name=lastTime,proto3" json:"lastTime,omitempty"`           // 持续时间，单位：秒，最大值2小时=2*60*60
	Context   string `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`              // 内容：消息内容
}

func (x *SYSMessageToUserReq) Reset() {
	*x = SYSMessageToUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SYSMessageToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SYSMessageToUserReq) ProtoMessage() {}

func (x *SYSMessageToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SYSMessageToUserReq.ProtoReflect.Descriptor instead.
func (*SYSMessageToUserReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{11}
}

func (x *SYSMessageToUserReq) GetToAll() uint32 {
	if x != nil {
		return x.ToAll
	}
	return 0
}

func (x *SYSMessageToUserReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SYSMessageToUserReq) GetBeginTime() uint32 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *SYSMessageToUserReq) GetLastTime() uint32 {
	if x != nil {
		return x.LastTime
	}
	return 0
}

func (x *SYSMessageToUserReq) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type SYSMessageToUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 0：成功；其他值：错误
}

func (x *SYSMessageToUserResp) Reset() {
	*x = SYSMessageToUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SYSMessageToUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SYSMessageToUserResp) ProtoMessage() {}

func (x *SYSMessageToUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SYSMessageToUserResp.ProtoReflect.Descriptor instead.
func (*SYSMessageToUserResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{12}
}

func (x *SYSMessageToUserResp) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GoodsValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsType  GoodsType `protobuf:"varint,1,opt,name=goods_type,json=goodsType,proto3,enum=com.hipoker.proto.web.GoodsType" json:"goods_type,omitempty"` // 物品的种类
	GoodsValue uint32    `protobuf:"varint,2,opt,name=goods_value,json=goodsValue,proto3" json:"goods_value,omitempty"`                                   // 物品的数量
	IsGet      uint32    `protobuf:"varint,3,opt,name=is_get,json=isGet,proto3" json:"is_get,omitempty"`                                                  // 0：无意义；1：没有得到；2：已经取到
}

func (x *GoodsValue) Reset() {
	*x = GoodsValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsValue) ProtoMessage() {}

func (x *GoodsValue) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsValue.ProtoReflect.Descriptor instead.
func (*GoodsValue) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{13}
}

func (x *GoodsValue) GetGoodsType() GoodsType {
	if x != nil {
		return x.GoodsType
	}
	return GoodsType_Goods_Invalid
}

func (x *GoodsValue) GetGoodsValue() uint32 {
	if x != nil {
		return x.GoodsValue
	}
	return 0
}

func (x *GoodsValue) GetIsGet() uint32 {
	if x != nil {
		return x.IsGet
	}
	return 0
}

type MailToUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint32        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	Title       string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Context     string        `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`                            // 内容
	GoodsValues []*GoodsValue `protobuf:"bytes,4,rep,name=goods_values,json=goodsValues,proto3" json:"goods_values,omitempty"` // 附件：用户向用户发送补偿、福利、赠送之类的用途
}

func (x *MailToUserReq) Reset() {
	*x = MailToUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailToUserReq) ProtoMessage() {}

func (x *MailToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailToUserReq.ProtoReflect.Descriptor instead.
func (*MailToUserReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{14}
}

func (x *MailToUserReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MailToUserReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MailToUserReq) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *MailToUserReq) GetGoodsValues() []*GoodsValue {
	if x != nil {
		return x.GoodsValues
	}
	return nil
}

type MailToUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 0：成功；其他值：错误
}

func (x *MailToUserResp) Reset() {
	*x = MailToUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailToUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailToUserResp) ProtoMessage() {}

func (x *MailToUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailToUserResp.ProtoReflect.Descriptor instead.
func (*MailToUserResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{15}
}

func (x *MailToUserResp) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type UserCountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCount uint32 `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
}

func (x *UserCountResp) Reset() {
	*x = UserCountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCountResp) ProtoMessage() {}

func (x *UserCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCountResp.ProtoReflect.Descriptor instead.
func (*UserCountResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{16}
}

func (x *UserCountResp) GetUserCount() uint32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

type WebUpdateParticesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                      // 用户的ID
	ParticesValue int32  `protobuf:"varint,2,opt,name=partices_value,json=particesValue,proto3" json:"partices_value,omitempty"` // 练习币的数值，注意：有正负
}

func (x *WebUpdateParticesReq) Reset() {
	*x = WebUpdateParticesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebUpdateParticesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebUpdateParticesReq) ProtoMessage() {}

func (x *WebUpdateParticesReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebUpdateParticesReq.ProtoReflect.Descriptor instead.
func (*WebUpdateParticesReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{17}
}

func (x *WebUpdateParticesReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WebUpdateParticesReq) GetParticesValue() int32 {
	if x != nil {
		return x.ParticesValue
	}
	return 0
}

type WebUpdateParticesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`                                 // 0：成功；其他值错误
	UserId       uint32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // 用户的id
	UserPartices int32  `protobuf:"varint,3,opt,name=user_partices,json=userPartices,proto3" json:"user_partices,omitempty"` // 用户现在的练习币
}

func (x *WebUpdateParticesResp) Reset() {
	*x = WebUpdateParticesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebUpdateParticesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebUpdateParticesResp) ProtoMessage() {}

func (x *WebUpdateParticesResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebUpdateParticesResp.ProtoReflect.Descriptor instead.
func (*WebUpdateParticesResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{18}
}

func (x *WebUpdateParticesResp) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *WebUpdateParticesResp) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WebUpdateParticesResp) GetUserPartices() int32 {
	if x != nil {
		return x.UserPartices
	}
	return 0
}

type WebSyncBalanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *WebSyncBalanceReq) Reset() {
	*x = WebSyncBalanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebSyncBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSyncBalanceReq) ProtoMessage() {}

func (x *WebSyncBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSyncBalanceReq.ProtoReflect.Descriptor instead.
func (*WebSyncBalanceReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{19}
}

func (x *WebSyncBalanceReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type WebSyncBalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *WebSyncBalanceResp) Reset() {
	*x = WebSyncBalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebSyncBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSyncBalanceResp) ProtoMessage() {}

func (x *WebSyncBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSyncBalanceResp.ProtoReflect.Descriptor instead.
func (*WebSyncBalanceResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{20}
}

func (x *WebSyncBalanceResp) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_web_proto protoreflect.FileDescriptor

var file_web_proto_rawDesc = []byte{
	0x0a, 0x09, 0x77, 0x65, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x63, 0x6f, 0x6d,
	0x2e, 0x68, 0x69, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x77,
	0x65, 0x62, 0x22, 0xf0, 0x01, 0x0a, 0x17, 0x57, 0x65, 0x62, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6e, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x63, 0x0a, 0x18, 0x57, 0x65, 0x62, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x31, 0x0a, 0x16, 0x57, 0x65,
	0x62, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x19, 0x0a,
	0x17, 0x57, 0x65, 0x62, 0x46, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x1a, 0x57, 0x65, 0x62, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x61, 0x72, 0x64, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x63, 0x61, 0x72, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xc8, 0x01, 0x0a, 0x1b, 0x57, 0x65, 0x62, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x61,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x53, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x68, 0x69, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x77, 0x65,
	0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x57, 0x50, 0x61, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x2f, 0x0a, 0x15, 0x43, 0x57, 0x50, 0x61, 0x79, 0x43, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x4a, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x54, 0x65, 0x78,
	0x61, 0x73, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x18, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x54, 0x65, 0x78, 0x61, 0x73, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x13, 0x53,
	0x59, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x54, 0x6f, 0x41, 0x6c, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2e, 0x0a, 0x14, 0x53, 0x59, 0x53, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x68,
	0x69, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x77, 0x65, 0x62,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x67, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x73, 0x47, 0x65, 0x74, 0x22, 0x9e, 0x01,
	0x0a, 0x0d, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x44, 0x0a, 0x0c, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x68, 0x69, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x28,
	0x0a, 0x0e, 0x4d, 0x61, 0x69, 0x6c, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2e, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x56, 0x0a, 0x14, 0x57, 0x65, 0x62, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x6d, 0x0a, 0x15, 0x57, 0x65, 0x62, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x22,
	0x2c, 0x0a, 0x11, 0x57, 0x65, 0x62, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a,
	0x12, 0x57, 0x65, 0x62, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x5a, 0x0a, 0x09, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x01, 0x12, 0x16,
	0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x77, 0x69, 0x6e, 0x73, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x5f,
	0x62, 0x6f, 0x6e, 0x75, 0x73, 0x10, 0x03, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x69, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77,
	0x65, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web_proto_rawDescOnce sync.Once
	file_web_proto_rawDescData = file_web_proto_rawDesc
)

func file_web_proto_rawDescGZIP() []byte {
	file_web_proto_rawDescOnce.Do(func() {
		file_web_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_proto_rawDescData)
	})
	return file_web_proto_rawDescData
}

var file_web_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_web_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_web_proto_goTypes = []interface{}{
	(GoodsType)(0),                      // 0: com.hipoker.proto.web.GoodsType
	(*WebUpdateBalanceRequest)(nil),     // 1: com.hipoker.proto.web.WebUpdateBalanceRequest
	(*WebUpdateBalanceResponse)(nil),    // 2: com.hipoker.proto.web.WebUpdateBalanceResponse
	(*WebFreezePlayerRequest)(nil),      // 3: com.hipoker.proto.web.WebFreezePlayerRequest
	(*WebFreezePlayerResponse)(nil),     // 4: com.hipoker.proto.web.WebFreezePlayerResponse
	(*WebTableInformationRequest)(nil),  // 5: com.hipoker.proto.web.WebTableInformationRequest
	(*TablePlayerInformation)(nil),      // 6: com.hipoker.proto.web.TablePlayerInformation
	(*WebTableInformationResponse)(nil), // 7: com.hipoker.proto.web.WebTableInformationResponse
	(*CWPayCallbackRequest)(nil),        // 8: com.hipoker.proto.web.CWPayCallbackRequest
	(*CWPayCallbackResponse)(nil),       // 9: com.hipoker.proto.web.CWPayCallbackResponse
	(*StandTexasTaskRequest)(nil),       // 10: com.hipoker.proto.web.StandTexasTaskRequest
	(*StandTexasTaskResponse)(nil),      // 11: com.hipoker.proto.web.StandTexasTaskResponse
	(*SYSMessageToUserReq)(nil),         // 12: com.hipoker.proto.web.SYSMessageToUserReq
	(*SYSMessageToUserResp)(nil),        // 13: com.hipoker.proto.web.SYSMessageToUserResp
	(*GoodsValue)(nil),                  // 14: com.hipoker.proto.web.GoodsValue
	(*MailToUserReq)(nil),               // 15: com.hipoker.proto.web.MailToUserReq
	(*MailToUserResp)(nil),              // 16: com.hipoker.proto.web.MailToUserResp
	(*UserCountResp)(nil),               // 17: com.hipoker.proto.web.UserCountResp
	(*WebUpdateParticesReq)(nil),        // 18: com.hipoker.proto.web.WebUpdateParticesReq
	(*WebUpdateParticesResp)(nil),       // 19: com.hipoker.proto.web.WebUpdateParticesResp
	(*WebSyncBalanceReq)(nil),           // 20: com.hipoker.proto.web.WebSyncBalanceReq
	(*WebSyncBalanceResp)(nil),          // 21: com.hipoker.proto.web.WebSyncBalanceResp
}
var file_web_proto_depIdxs = []int32{
	6,  // 0: com.hipoker.proto.web.WebTableInformationResponse.players:type_name -> com.hipoker.proto.web.TablePlayerInformation
	0,  // 1: com.hipoker.proto.web.GoodsValue.goods_type:type_name -> com.hipoker.proto.web.GoodsType
	14, // 2: com.hipoker.proto.web.MailToUserReq.goods_values:type_name -> com.hipoker.proto.web.GoodsValue
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_web_proto_init() }
func file_web_proto_init() {
	if File_web_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebUpdateBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebUpdateBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebFreezePlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebFreezePlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebTableInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TablePlayerInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebTableInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CWPayCallbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CWPayCallbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandTexasTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandTexasTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SYSMessageToUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SYSMessageToUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailToUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailToUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebUpdateParticesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebUpdateParticesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebSyncBalanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebSyncBalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_proto_goTypes,
		DependencyIndexes: file_web_proto_depIdxs,
		EnumInfos:         file_web_proto_enumTypes,
		MessageInfos:      file_web_proto_msgTypes,
	}.Build()
	File_web_proto = out.File
	file_web_proto_rawDesc = nil
	file_web_proto_goTypes = nil
	file_web_proto_depIdxs = nil
}
